apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mem-stress
  namespace: did
spec:
  mode: all
  selector:
    labelSelectors:
      stress: me
  containerNames:
    - dummy
  stressors:
    memory:
      workers: 1
      size: 400MiB
      options: [""]
  duration: "1h"
