{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kubelet_target_reserved_memory_bytes{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_target_reserved_memory_bytes_machine_type{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_reserved_memory_bytes{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_target_reserved_cpu{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_current_reserved_cpu{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_target_reserved_disk_bytes{}) by (instance)"
    },
    {
     "expr": "sum(node_memory_MemAvailable_percent{}) by (instance)"
    },
    {
     "expr": "sum(node_cgroup_system_slice_min_guaranteed_cpu - node_cgroup_system_slice_cpu_percent) by (instance)"
    },
    {
     "expr": "sum(node_cgroup_kubepods_min_guaranteed_cpu - node_cgroup_kubepods_cpu_percent) by (instance)"
    },
    {
     "expr": "sum(node_disk_available_percent{}) by (instance)"
    },
    {
     "expr": "sum(node_cgroup_system_slice_memory_working_set_bytes{}) by (instance)"
    },
    {
     "expr": "sum(node_cgroup_kubepods_memory_working_set_bytes{}) by (instance)"
    },
    {
     "expr": "sum(kubelet_target_reserved_cpu_machine_type{}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory over-reservation actual vs. based on machine type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kubelet_target_reserved_memory_bytes_machine_type{} - kubelet_target_reserved_memory_bytes{}) > 0)"
    }
   ]
  },
  {
   "title": "Memory under-reservation actual vs. based on machine type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(sum((kubelet_target_reserved_memory_bytes_machine_type{} - kubelet_target_reserved_memory_bytes{}) < 0))"
    }
   ]
  },
  {
   "title": "CPU over-reservation actual vs. based on machine type (in cores)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kubelet_target_reserved_cpu_machine_type{} - kubelet_target_reserved_cpu{}) / 1000 > 0)"
    }
   ]
  },
  {
   "title": "CPU under-reservation actual vs. based on machine type (in cores)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(sum((kubelet_target_reserved_cpu_machine_type{} - kubelet_target_reserved_cpu{}) / 1000 < 0))"
    }
   ]
  },
  {
   "title": "Recommendation vs. Actual reservation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Maximum (recommended CPU reservation minus actual CPU reservation) (1000m=1core)",
   "type": "timeseries",
   "description": "Note: A Negative value means overreservation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kubelet_target_reserved_cpu-kubelet_current_reserved_cpu)"
    }
   ]
  },
  {
   "title": "Maximum (recommended memory reservation minus actual reservation)",
   "type": "timeseries",
   "description": "Please note that a negative value means that we are currently over-reserving.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "max(kubelet_target_reserved_memory_bytes - kubelet_reserved_memory_bytes)"
    }
   ]
  },
  {
   "title": "Reservations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum recommended memory reservation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(kubelet_target_reserved_memory_bytes)"
      }
     ]
    },
    {
     "title": "Maximum recommended CPU reservation (in millicores m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "max(kubelet_target_reserved_cpu)"
      }
     ]
    },
    {
     "title": "Maximum recommended disk reservation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(kubelet_target_reserved_disk_bytes)"
      }
     ]
    },
    {
     "title": "Maximum recommended disk reservation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(kubelet_target_reserved_disk_percent)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minimum Node Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      { "expr": "min(node_memory_MemAvailable)" }
     ]
    },
    {
     "title": "Minimum Node Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(node_memory_MemAvailable_percent)"
      }
     ]
    },
    {
     "title": "Minimum system.slice cgroup free CPU time (min. guaranteed by CPU Shares minus CPU usage for cgroup)",
     "type": "timeseries",
     "description": "NOTE: having 0 or negative number here only means that the cgroup used all of its \"fair\" share of CPU time. This can be exceeded if another cgroup (such as kubepods) does not use its fair share. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(node_cgroup_system_slice_min_guaranteed_cpu - node_cgroup_system_slice_cpu_percent)"
      }
     ]
    },
    {
     "title": "Minimum kubepods cgroup free CPU time (min. guaranteed by CPU Shares minus CPU usage for cgroup)",
     "type": "timeseries",
     "description": "NOTE: having a 0 or negative number here only means that the cgroup used all of its \"fair\" share of CPU time. This can be exceeded if another cgroup (such as system.slice) does not use its fair share. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(node_cgroup_kubepods_min_guaranteed_cpu - node_cgroup_kubepods_cpu_percent)"
      }
     ]
    },
    {
     "title": "Maximum CPU Usage over all cores (100% = all cores used 100%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(node_cpu_usage_percent/node_num_cpu_cores)"
      }
     ]
    },
    {
     "title": "Minimum Node Disk Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "min(node_disk_available_percent)"
      }
     ]
    },
    {
     "title": "Minimum Node Disk Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      { "expr": "min(node_disk_available_bytes)" }
     ]
    }
   ]
  },
  {
   "title": "Other memory stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum system.slice cgroup working set size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_cgroup_system_slice_memory_working_set_bytes)"
      }
     ]
    },
    {
     "title": "Maximum kubepods cgroup working set size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_cgroup_kubepods_memory_working_set_bytes)"
      }
     ]
    },
    {
     "title": "Maximum containerd cgroup working set size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_cgroup_containerd_service_memory_working_set_bytes)"
      }
     ]
    },
    {
     "title": "Maximum kubelet cgroup working set size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_cgroup_kubelet_service_memory_working_set_bytes)"
      }
     ]
    }
   ]
  },
  {
   "title": "Other disk stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum size pod logs (/var/log/pods)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      { "expr": "max(node_pod_logs_size)" }
     ]
    },
    {
     "title": "Maximum size containerd snapshotter (/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_containerd_overlayfs_snapshotter_size_bytes)"
      }
     ]
    },
    {
     "title": "Maximum size containerd content store (/var/lib/containerd/io.containerd.content.v1.content)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_containerd_content_store_size_bytes)"
      }
     ]
    },
    {
     "title": "Maximum size of pod volumes on root disk (/var/lib/kubelet/pods, excluding CSI, hostPath, tmpfs emptyDir)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_pod_volumes_size_bytes)"
      }
     ]
    },
    {
     "title": "Maximum size of kubelet plugins (/var/lib/kubelet/plugins)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      { "expr": "max(kubelet_plugin_size_bytes)" }
     ]
    },
    {
     "title": "Maximum size of containerd state (/run/containerd)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "max(node_containerd_state_size_bytes)"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Disk",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubelet_target_reserved_disk_bytes{job=\"reserved-resources-recommender\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Recommendation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recommended reserved disk percent",
   "type": "timeseries",
   "description": "The % of the root disk that should be reserved for non-pod processes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kubelet_target_reserved_disk_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Recommended reserved disk bytes",
   "type": "timeseries",
   "description": "The amount of bytes on the root disk that should be reserved for non-pod processes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_target_reserved_disk_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  { "title": "Root Disk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Available disk space (root disk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_disk_available_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Available disk space  (root disk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_disk_available_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Filesystem Reserved Bytes (root disk)",
   "type": "stat",
   "description": "This is the amount of bytes reseverd by the filesystem (not by the kubelet!)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_reserved_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  { "title": "Containerd + Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Containerd Snapshotter Size (/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs)",
   "type": "timeseries",
   "description": "The Snapshotter contains the unpacked layers (from the content store) + the working directory of every container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_containerd_overlayfs_snapshotter_size_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Containerd State Size (/run/containerd)",
   "type": "timeseries",
   "description": "/run/containerd excluding rootfs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_containerd_state_size_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Pod Logs bytes (/var/log/pods)",
   "type": "timeseries",
   "description": "The size of the pod's logs in /var/log/pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_pod_logs_size{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Containerd Content Store Size (/var/lib/containerd/io.containerd.content.v1.content/)",
   "type": "timeseries",
   "description": "Contains .tar archives of unpacked images in the containerd content store.\nLocated at: /var/lib/containerd/io.containerd.content.v1.content/\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_containerd_content_store_size_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Pod Volume Size (on root-disk only) (/var/lib/kubelet/pods )",
   "type": "timeseries",
   "description": "The size of the pod volumes that use the root disk. Excludes CSI volumes for network-attached storage. emptyDir with tmpfs backing and hostPath. Because hostPath is excluded, this metric can be incorrect for nodes hosting pods that write to disk using hostPath volumes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_pod_volumes_size_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubelet plugins size (/var/lib/kubelet/plugins)",
   "type": "timeseries",
   "description": "The size of the kubelet's plugins.\nCan be determined using: du -sb --exclude=\"csi\" /var/lib/kubelet/plugins",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "kubelet_plugin_size_bytes{instance=~\"$Node\"}"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubelet_target_reserved_cpu{job=\"reserved-resources-recommender\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Recommendation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubelet current reserved CPU vs Target reserved CPU",
   "type": "timeseries",
   "description": "in m (e.g 80m == 8% of one core)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kubelet_current_reserved_cpu{instance=~\"$Node\"}"
    },
    {
     "expr": "kubelet_target_reserved_cpu{instance=~\"$Node\"}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "System.slice usage vs. min. guaranteed by CPU shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_cgroup_system_slice_min_guaranteed_cpu{instance=~\"$Node\"}"
    },
    {
     "expr": "node_cgroup_system_slice_cpu_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubepods usage vs. min. guaranteed by CPU shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "node_cgroup_kubepods_cpu_percent{instance=~\"$Node\"}"
    },
    {
     "expr": "node_cgroup_kubepods_min_guaranteed_cpu{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "System.slice current CPU usage (100 = one core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "node_cgroup_system_slice_cpu_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "kubepods cgroup CPU usage (100 == one core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "node_cgroup_kubepods_cpu_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Number CPU cores vs.  min. guaranteed CPU for system.slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "node_cgroup_system_slice_min_guaranteed_cpu{instance=~\"$Node\"}"
    },
    {
     "expr": "node_num_cpu_cores{instance=~\"$Node\"}"
    }
   ]
  }
 ]
}
{
 "title": "Memory",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubelet_target_reserved_memory_percent{job=\"reserved-resources-recommender\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reserved Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Target reserved vs. actually reserved",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_reserved_memory_bytes{instance=~\"$Node\"}"
    },
    {
     "expr": "kubelet_target_reserved_memory_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Node stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node memory available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemAvailable{instance=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Node Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_percent{instance=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Not-evictable memory used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "node_memory_used{instance=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Not-evictable memory used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_memory_used_percent{instance=~\"$Node\"}"
      }
     ]
    }
   ]
  },
  { "title": "cgroup stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "System.slice cgroup memory working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_system_slice_memory_working_set_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "System.slice cgroup memory working set % total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_system_slice_memory_working_set_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubepods cgroup memory working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_kubepods_memory_working_set_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubepods cgroup memory working set % total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_kubepods_memory_working_set_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Containerd cgroup memory working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_containerd_service_memory_working_set_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Containerd cgroup memory working set % total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_containerd_service_memory_working_set_percent{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubelet cgroup memory working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_kubelet_service_memory_working_set_bytes{instance=~\"$Node\"}"
    }
   ]
  },
  {
   "title": "Kubelet cgroup memory working set % total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_cgroup_kubelet_service_memory_working_set_percent{instance=~\"$Node\"}"
    }
   ]
  }
 ]
}