apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.privileged
  labels:
    pod: d060239
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-shoot-apiserver: allowed
  name: "debugpod-d060239-<replace>" # set by script based on node name
spec:
  priorityClassName: system-cluster-critical
  containers:
#    - image: nicolaka/netshoot
    - image: eu.gcr.io/sap-se-gcr-k8s-public/eu_gcr_io/gardener-project/gardener/ops-toolbelt:0.22.0-mod1
      imagePullPolicy: Always
      name: root-container
      #resources:
#       QoS guaranteed to make sure evicted late by kubelet and Linux OOM killer (oom_score_adj is low)
#        requests:
#          memory: "1Gi"
#          cpu: "500m"
       # limits:
       #   memory: "1Gi"
       #   cpu: "500m"
      securityContext:
        privileged: true
        runAsUser: 0
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /host
          name: root-volume
#        - mountPath: /var/run/docker.sock
#          name: docker-socket
#        - mountPath: /var/run/containerd/containerd.sock
#          name: containerd-socket
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostNetwork: true
  hostPID: true
#  nodeName: ip-10-180-29-202.eu-west-1.compute.internal #set by script
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
#      <tolerations_array>
  - effect: "PreferNoSchedule"
    key: "deployment.machine.sapcloud.io/prefer-no-schedule"
    value: "True"
    operator: ""
  - effect: "NoSchedule"
    key: "node.kubernetes.io/unschedulable"
    value: ""
    operator: ""
  - effect: "PreferNoSchedule"
    key: "NODE_TYPE"
    value: "app"
    operator: ""
  - effect: "PreferNoSchedule"
    key: "LANDSCAPE"
    value: "qa"
    operator: ""
  - effect: "NoSchedule"
    key: "node.kubernetes.io/disk-pressure"
    value: ""
    operator: ""
  volumes:
    - hostPath:
        path: /
        type: ""
      name: root-volume
#    - hostPath:
#        # on Gardener nodes still always available even on containerd-only nodes
#        path: /var/run/docker.sock
#        type: ""
#      name: docker-socket
#    - hostPath:
#        path: /var/run/containerd/containerd.sock
#        type: ""
#      name: containerd-socket


