# Run from nerdctl in GL like so:
#  nerdctl run -ti --rm -v /sys/kernel/debug:/sys/kernel/debug -v /sys/fs/cgroup:/sys/fs/cgroup -v /sys/fs/bpf:/sys/fs/bpf --privileged --net host debian:bookworm /usr/bin/bash
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.privileged
  labels:
    pod: d060239
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-shoot-apiserver: allowed
  name: "ebpf-debugpod-gl-934-7" # set by script based on node name
spec:
  priorityClassName: system-cluster-critical
  containers:
    - image: danielfoehrkn/debian-gardenlinux-bpf:934.7
      command: ["/usr/bin/bash"]
      imagePullPolicy: Always
      name: root-container
      #resources:
#       QoS guaranteed to make sure evicted late by kubelet and Linux OOM killer (oom_score_adj is low)
#        requests:
#          memory: "1Gi"
#          cpu: "500m"
       # limits:
       #   memory: "1Gi"
       #   cpu: "500m"
      securityContext:
        privileged: true
        runAsUser: 0
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /host
          name: root-volume
        - mountPath: /sys/kernel/debug
          name: kernel-debug
        - mountPath: /sys/fs/cgroup
          name: cgroupfs
        - mountPath: /sys/fs/bpf
          name: bpf
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostNetwork: true
  hostPID: true
  nodeName: shoot--coresrv--zerosearch-worker-core-tmp-z2-64466-ds9xr
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: pool.worker.gardener.cloud/dedicated-for
      operator: Equal
      value: etcd
  volumes:
    - hostPath:
        path: /
        type: ""
      name: root-volume
    - hostPath:
        path: /sys/kernel/debug
        type: ""
      name: kernel-debug
    - hostPath:
        path: /sys/fs/cgroup
        type: ""
      name: cgroupfs
    - hostPath:
        path: /sys/fs/bpf
        type: ""
      name: bpf



