apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: gardener.privileged
  labels:
    app: root
    component: reserved-resources-recommender
    networking.gardener.cloud/to-dns: allowed
    networking.gardener.cloud/to-shoot-apiserver: allowed
  name: reserved-resources-recommender
spec:
#  priorityClassName: system-cluster-critical
  containers:
    - image: eu.gcr.io/gardener-project/gardener/reserved-resources-recommender:latest
      imagePullPolicy: Always
      name: reconciler
      env:
        - name: PERIOD
          value: "30s"
        - name: MEMORY_SAFETY_MARGIN_ABSOLUTE
          value: 400Mi
        - name: CGROUPS_HIERARCHY_ROOT
          value: "/sys/fs/cgroup"
        - name: CGROUPS_CONTAINERD_ROOT
          value: "system.slice/containerd.service"
        - name: CGROUPS_KUBELET_ROOT
          value: "system.slice/kubelet.service"
          # also adjust Volume if this is changed
        - name: KUBELET_DIRECTORY
          value: "/var/lib/kubelet"
        - name: ENFORCE_RECOMMENDATION
          value: "false"
      resources:
        requests:
          memory: "16Mi"
          cpu: "20m"
#        limits:
#          memory: "30Mi"
#          cpu: "40m"
      securityContext:
        privileged: true
        runAsUser: 0
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - name: kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: cgroup-hierarchy
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: dev
          mountPath: /dev
          readOnly: true
        - name: containerd-root
          mountPath: /var/lib/containerd
          readOnly: true
        - name: containerd-state
          mountPath: /run/containerd
          readOnly: true
        - name: pod-logs
          mountPath: /var/log/pods
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostNetwork: true
  hostPID: true
  nodeName: shoot--cs-core--ghrunner-app-z1-54b5c-6lvcs
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: WorkGroup
      operator: Equal
      value: ws
    - effect: NoSchedule
      key: WorkGroup
      operator: Equal
      value: ws
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: pool.worker.gardener.cloud/dedicated-for
      operator: Equal
      value: etcd
  volumes:
    - name: kubelet
      hostPath:
        path: /var/lib/kubelet
        type: "Directory"
    - name: cgroup-hierarchy
      hostPath:
        path: /sys/fs/cgroup
        type: "Directory"
    - name: dev
      hostPath:
        path: /dev
        type: "Directory"
    - name: containerd-root
      hostPath:
        path: /var/lib/containerd
        type: "Directory"
    - name: containerd-state
      hostPath:
        path: /run/containerd
        type: "Directory"
    - name: pod-logs
      hostPath:
        path: /var/log/pods
        type: "Directory"

      #    - name: proc
#      hostPath:
#        path: /proc/meminfo
#        type: "Directory"


