  root@machine-shoot--local--e2e-wake-up-local-7bd95-csvd7:/# cat /var/lib/kubelet/config/kubelet
  apiVersion: kubelet.config.k8s.io/v1beta1
  authentication:
    anonymous:
      enabled: false
    webhook:
      cacheTTL: 2m0s
      enabled: true
    x509:
      clientCAFile: /var/lib/kubelet/ca.crt
  authorization:
    mode: Webhook
    webhook:
      cacheAuthorizedTTL: 5m0s
      cacheUnauthorizedTTL: 30s
  cgroupDriver: systemd
  cgroupRoot: /
  cgroupsPerQOS: true
  clusterDNS:
    - 10.4.0.10
  clusterDomain: cluster.local
  containerLogMaxSize: 100Mi
  cpuCFSQuota: true
  cpuManagerPolicy: none
  cpuManagerReconcilePeriod: 10s
  enableControllerAttachDetach: true
  enableDebuggingHandlers: true
  enableServer: true
  enforceNodeAllocatable:
    - pods
  eventBurst: 50
  eventRecordQPS: 50
  evictionHard:
    imagefs.available: 5%
    imagefs.inodesFree: 5%
    memory.available: 100Mi
    nodefs.available: 5%
    nodefs.inodesFree: 5%
  evictionMaxPodGracePeriod: 90
  evictionMinimumReclaim:
    imagefs.available: 0Mi
    imagefs.inodesFree: 0Mi
    memory.available: 0Mi
    nodefs.available: 0Mi
    nodefs.inodesFree: 0Mi
  evictionPressureTransitionPeriod: 4m0s
  evictionSoft:
    imagefs.available: 10%
    imagefs.inodesFree: 10%
    memory.available: 200Mi
    nodefs.available: 10%
    nodefs.inodesFree: 10%
  evictionSoftGracePeriod:
    imagefs.available: 1m30s
    imagefs.inodesFree: 1m30s
    memory.available: 1m30s
    nodefs.available: 1m30s
    nodefs.inodesFree: 1m30s
  failSwapOn: false
  fileCheckFrequency: 20s
  hairpinMode: promiscuous-bridge
  httpCheckFrequency: 20s
  imageGCHighThresholdPercent: 50
  imageGCLowThresholdPercent: 40
  imageMinimumGCAge: 2m0s
  kind: KubeletConfiguration
  kubeAPIBurst: 50
  kubeAPIQPS: 50
  kubeReserved:
    cpu: 80m
    memory: 1Gi
    pid: 20k
  logging:
    flushFrequency: 0
    options:
      json:
        infoBufferSize: "0"
    verbosity: 0
  maxOpenFiles: 1000000
  maxPods: 110
  memorySwap: {}
  nodeStatusReportFrequency: 0s
  nodeStatusUpdateFrequency: 0s
  protectKernelDefaults: true
  registerWithTaints:
    - effect: NoSchedule
      key: node.gardener.cloud/critical-components-not-ready
  registryBurst: 20
  registryPullQPS: 10
  resolvConf: /etc/resolv.conf
  rotateCertificates: true
  runtimeRequestTimeout: 2m0s
  serializeImagePulls: false
  serverTLSBootstrap: true
  shutdownGracePeriod: 0s
  shutdownGracePeriodCriticalPods: 0s
  streamingConnectionIdleTimeout: 5m0s
  syncFrequency: 1m0s
  volumePluginDir: /var/lib/kubelet/volumeplugins
  volumeStatsAggPeriod: 1m0s